---

- name: Set ip forwarding in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
  become: yes

# - name: Generate fingerprints from nmap
#   shell:
