---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.yum.yml
  when: ansible_os_family == 'RedHat'

- include: install_honeyd.yml

- include: prepare_conf_dirs.yml

- include: systemd.yml

- include: database.yml

- include: configure.yml

- name: Start the honeyd service
  service:
    name: honeyd.service
    state: started
    enabled: yes
  become: yes
