---

- import_tasks: install.deb.yml
  when: ansible_os_family == 'Debian'

#- import_tasks: install.yum.yml
  #when: ansible_os_family == 'RedHat'

- import_tasks: install_honeyd.yml

- import_tasks: prepare_conf_dirs.yml

- import_tasks: systemd.yml

- import_tasks: database.yml

- import_tasks: configure.yml
