---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.yum.yml
  when: ansible_os_family == 'RedHat'

- include: install_honeyd.yml

- include: database.yml

- include: configure.yml
