---

- name: Install named dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libevent-dev
      - libdumbnet-dev
      - libpcap-dev
      - libpcre3-dev
      - libedit-dev
      - bison
      - flex
      - libtool
      - automake
      # unnamed dependencies
      - zlib1g-dev
      - make
      # utilities
      - unzip
      - python


