---

- name: Check if honeyd is installed
  stat:
    path: "{{ honeyd_install_dir }}/bin/honeyd"
  register: honeyd_exists

- name: Ensure gcc-9 and g++-9 are installed
  apt:
    name:
      - gcc-9
      - g++-9
    state: present
    update_cache: yes
  when: not honeyd_exists.stat.exists

- name: Download latest honeyd from DataSoft
  unarchive:
    src: "{{ honeyd_repo }}"
    dest: /tmp
    remote_src: yes
    list_files: yes
  when: not honeyd_exists.stat.exists

- name: Download latest honeyd from Provos
  unarchive:
    src: "{{ honeyd_provos_repo }}"
    dest: /tmp
    remote_src: yes
    list_files: yes
  register: provos_dir
  when: not honeyd_exists.stat.exists and honeyd_provos_scripts

- name: Build and install honeyd
  shell: |
    # Copied directly from (DataSoft) HoneyD README.md
    ./autogen.sh
    ./configure --prefix={{ honeyd_install_dir }}
    make
    sudo make install
  args:
    chdir: "/tmp/Honeyd-master"
  environment:
    CC: "gcc-9"
    CXX: "g++-9"
  when: not honeyd_exists.stat.exists
