---

- name: Check if honeyd is installed
  stat:
    path: /usr/bin/honeyd
  register: honeyd_exists

- name: Download latest honeyd from DataSoft
  unarchive:
    src: "{{ honeyd_repo }}"
    dest: /tmp
    remote_src: yes
    list_files: yes
  when: not honeyd_exists.stat.exists

- name: Download latest honeyd from Provos
  unarchive:
    src: "{{ honeyd_provos_repo }}"
    dest: /tmp
    remote_src: yes
    list_files: yes
  register: provos_dir
  when: not honeyd_exists.stat.exists and honeyd_provos_scripts

- name: Build and install honeyd
  shell: |
    # Copied directly from (DataSoft) HoneyD README.md
    ./autogen.sh
    ./configure
    make
    sudo make install
  args:
    chdir: "/tmp/Honeyd-master"
  when: not honeyd_exists.stat.exists
