---

- name: Create /etc folder
  file:
    path: /etc/honeyd
    owner: root
    group: root
    mode: 0755
    state: directory
  when: not honeyd_exists.stat.exists

- name: Create conf.d folder
  file:
    path: /etc/honeyd/conf.d
    owner: root
    group: root
    mode: 0755
    state: directory
  when: not honeyd_exists.stat.exists and (honeyd_split_config or ( honeyd_use_config != '' ))

- name: Copy db files to /etc
  shell: cp -a {nmap-mac-prefixes,nmap-os-db,pf.os,nmap.assoc,xprobe2.conf} /etc/honeyd
  args:
    executable: /bin/bash
    chdir: "/usr/share/honeyd"
  when: not honeyd_exists.stat.exists

- name: Copy Provos' scripts to lib
  shell: |
    mkdir -p /usr/share/honeyd/scripts/original
    cp -r /tmp/"{{ provos_dir.files[1] }}"scripts/* /usr/share/honeyd/scripts/original/
  args:
    executable: /bin/bash
  when: not honeyd_exists.stat.exists

- name: Upload custom scripts
  template:
    src: "{{ item }}"
    dest: "/usr/share/honeyd/scripts/custom/{{ item | replace('.j2', '') }}"
    mode: 0755
  with_items: "{{ honeyd_custom_scripts }}"

- name: Create log directory
  file:
    path: /var/log/honeyd
    owner: nobody
    group: nogroup
    mode: 0755
    state: directory
  when: not honeyd_exists.stat.exists
