---

- name: Set permissions for installation folder
  file:
    path: "{{ honeyd_install_dir }}"
    owner: root
    group: root
    mode: 0700
    state: directory

- name: Create conf.d folder
  file:
    path: "{{ honeyd_install_dir }}/conf.d"
    owner: root
    group: root
    mode: 0700
    state: directory
  when: not honeyd_exists.stat.exists and (honeyd_split_config or ( honeyd_use_config != '' ))

- name: Copy Provos' scripts to lib
  block:
    - file:
        path: "{{ honeyd_install_dir }}/share/honeyd/scripts/original"
        state: directory
    - shell: |
        cp -r /tmp/{{ provos_dir.files[1] }}scripts/* {{ honeyd_install_dir }}/share/honeyd/scripts/original/
      args:
        executable: /bin/bash
  when: not honeyd_exists.stat.exists

- name: Create custom script directory
  file:
    path: "/usr/share/honeyd/scripts/custom/"
    state: directory

- name: Upload custom scripts
  template:
    src: "{{ item }}"
    dest: "{{ honeyd_install_dir }}/share/honeyd/scripts/custom/{{ item | basename | replace('.j2', '') }}"
    mode: 0755
  loop: "{{ honeyd_custom_scripts }}"

- name: Create log directory
  file:
    path: /var/log/honeyd
    owner: nobody
    group: nogroup
    mode: 0755
    state: directory
  when: not honeyd_exists.stat.exists
